---
- name: container
  hosts: client
  tasks:

  - name: Creating Test Environment.
    docker:
     name: seltestserver
     image: hemqa/testserverbase:v2
     detach: yes
     hostname: selserver
     state: started
     stdin_open: yes
     volumes:
       - /var/lib/jenkins/workspace/seltest:/root
       - /root/.m2:/root/.m2

  - name: Executing Selenium test cases on container.
    script: dockercall.sh seltestserver

  - name: Updating user changes.
    command: chown -R jenkins:jenkins *